import { HTMLTable } from "@blueprintjs/core";
import axios from "axios";
import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import useSwr from "swr";
import AppBar from "../components/appbar";
import styles from "../styles/Home.module.css";

// props: any is definitely best practices, dont @ me
const Home: NextPage = (props: any) => {
  const { data, error } = useSwr(
    "https://ranked.ddns.net/api/top?limit=10",
    fetcher
  );

  if (error) return <div>Failed to load.</div>;
  if (!data) return <div>Loading...</div>;

  return (
    <div className={styles.container}>
      <Head>
        <title>Homepage | Mindustry Ranked</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <AppBar />
        <HTMLTable striped={true}>
          <thead>
            <tr>
              <th>Place</th>
              <th>Name</th>
              <th>Rating</th>
              <th>Rank</th>
            </tr>
          </thead>
          <tbody>
            {data.playerList.map((player: any, index: number) => (
              <tr key={index}>
                <td>{index + 1}</td>
                <td>{player.name}</td>
                <td>{player.ratings["1v1"].rating}</td>
                <td>
                  {(() => {
                    // totally best practices
                    for (let i = 0; i < props.ranks.length; i++) {
                      if (
                        player.ratings["1v1"].rating < props.ranks[i].startsAt
                      )
                        return props.ranks[i - 1]?.name;
                    }
                  })()}
                </td>
              </tr>
            ))}
          </tbody>
        </HTMLTable>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
};

const fetcher = (url: string) => axios.get(url).then((res) => res.data);

export const getStaticProps: GetStaticProps = () => {
  return new Promise((resolve) => {
    axios
      .get("https://ranked.ddns.net/api/ranks")
      .then((res) => resolve({ props: { ranks: res.data } }));
  });
};

// export const getStaticProps: GetStaticProps = () =>
//   axios.get("https://ranked.ddns.net/api/ranks").then((res) => res.data);

export default Home;
