import axios from "axios";
import Head from "next/head";
import { useRouter } from "next/router";
import useSwr from "swr";
import AppBar from "../../components/appbar";
import styles from "../../styles/Home.module.css";
import { getNames } from "../../util";

export default function Match() {
  const router = useRouter();
  const { id } = router.query;

  const { data, error } = useSwr(
    `https://ranked.ddns.net/api/match?matchId=${id}`,
    (url: string) => axios.get(url).then((res) => res.data)
  );

  if (typeof id !== "string") return <div>Invalid id type</div>;
  if (error) return <div>Failed to load.</div>;
  if (!data) return <div>Loading...</div>;
  console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Homepage | Mindustry Ranked</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <AppBar />
        <h1>Match #{data.match_id}</h1>
        {getNames(data.players)}
        Map: {data.map}
        <br />
        {isNaN(data.finished_at)
          ? "Ongoing"
          : `Duration: ${Math.round(
              (data.finished_at - data.started_at) / 60000
            )} minutes`}
      </main>
    </div>
  );
}
